version: 2

jobs:

  build:
    machine: true
    parallelism: 2
    working_directory: ~/booking
    parallelism: 1
    steps:

      - checkout

      # NOTE: Circle has an outdated version of docker-compose, this will install
      #   a more modern version.
      # However, Circle seems to lock down the `/usr/local/bin` directory, hence the non-standard install location
      # Know that all docker-compose commands will need to use this path.
      - run:
          name: Install Docker Compose
          command: |
            set -x
            sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > ~/booking/docker-compose
            sudo chmod +x ~/booking/docker-compose

      - run:
          name: Docker check
          command: |
              docker --version
              ~/booking/docker-compose --version


      - persist_to_workspace:
          root: ~/booking
          paths:
            - ./*


  unit-python:
    machine: true
    docker_layer_caching: true
    parallelism: 1
    working_directory: ~/booking
    steps:
      - attach_workspace:
          at: ~/booking

      - run:
          command: sudo ~/booking/docker-compose build web

      - run:
          name: Run Django Tests!!!!!1!!
          command: |
              sudo ~/booking/docker-compose run web ./scripts/cmd-test.sh


  unit-js:
    machine: true
    docker_layer_caching: true
    parallelism: 1
    working_directory: ~/booking
    steps:
      - attach_workspace:
          at: ~/booking

      - restore_cache:
          keys:
            - node-modules-v1-{{ checksum "./booking/static/js/app/package.json" }}

      - run:
          command: sudo ~/booking/docker-compose build web-js

      - save_cache:
          key: node-modules-v1-{{ checksum "./booking/static/js/app/package.json" }}
          paths:
            - ./booking/static/js/app/node_modules/

      - run:
          name: Run Javascript Tests!!!!!1!!
          command: |
              sudo ~/booking/docker-compose run web-js npm run build


  deploy:
    machine: true
    docker_layer_caching: true
    parallelism: 1
    working_directory: ~/booking
    steps:
      - attach_workspace:
          at: ~/booking
      - run:
          command: env

      - restore_cache:
          keys:
            - node-modules-v1-{{ checksum "./booking/static/js/app/package.json" }}

      - run:
          name: Deploy to sandbox env
          command: |
            cd ~/booking/

            # Install dependencies
            pip install -r ./infra/requirements.txt

            # Build
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./infra/deploy.py --env-file ./infra/config/booking-stage.yml
            else
              BRANCH_NAME=$(echo $CIRCLE_BRANCH | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)
              ./infra/deploy.py --env-file ./infra/config/booking-stage.yml --branch=$BRANCH_NAME
            fi

      - save_cache:
          key: node-modules-v1-{{ checksum "./booking/static/js/app/package.json" }}
          paths:
            - ./booking/static/js/app/node_modules/

workflows:
  version: 2
  build:
    jobs:
      - build
      - unit-python:
            requires:
              - build
      - unit-js:
            requires:
              - build
      - deploy:
            requires:
              - unit-python
              - unit-js
            filters:
              branches:
                  ignore: /production/
